### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 271: character maps to <undefined>

### ISSUE THREAD

**Issue by pvdongen** [VTTI/gaze-fixation-and-object-saliency#2]
Hi,
I have been trying to run your code on a Windows machine and some parts work perfectly but others give errors. The get_gaze.py, estimate_front_angle.py, and filter_csv.py work perfectly fine. The gaze_overlay.py I haven't used.
- heatmap_overlay.py gives me the following error:

```

(gaze) C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master>python heatmap_overlay.py  --face C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master\Videos\face_ex.mp4 --front C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master\Videos\front_ex.mp4 --config C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master\config.yaml --output_folder C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master\Videos
heatmap_overlay.py:15: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
[ERROR:0@5.004] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (166) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): --face in function 'cv::icvExtractPattern'  


True
[ERROR:0@5.023] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (597) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): --front\heatmap_--face in function 'cv::icvExtra\PD\ctPattern'


Traceback (most recent call last):
  File "heatmap_overlay.py", line 73, in <module>
    config = yaml.safe_load(stream)
  File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\PD\miniconda3\envs\gaze\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 271: character maps to <undefined>

```

Environment:

Python 3.8.0
Numpy 1.23.2
Pytorch 1.10.1 (py3.8_cuda11.3_cudnn8_0)
Torchvision 0.11.2 (py38_cu113)
Opencv-python 4.6.0.66

**Comment by pvdongen** [comment]
> Hi, I have been trying to run your code on a Windows machine and some parts work perfectly but others give errors. The get_gaze.py, estimate_front_angle.py, and filter_csv.py work perfectly fine. The gaze_overlay.py I haven't used.
> 
> * heatmap_overlay.py gives me the following error:
> 
> ```
> 
> (gaze) C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master>python heatmap_overlay.py  --face C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master\Videos\face_ex.mp4 --front C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master\Videos\front_ex.mp4 --config C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master\config.yaml --output_folder C:\Users\PD\Downloads\gaze-fixation-and-object-saliency-master\Videos
> heatmap_overlay.py:15: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
>   from scipy.ndimage.filters import gaussian_filter
> [ERROR:0@5.004] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (166) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:
> 
> OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): --face in function 'cv::icvExtractPattern'  
> 
> 
> True
> [ERROR:0@5.023] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (597) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:
> 
> OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): --front\heatmap_--face in function 'cv::icvExtra\PD\ctPattern'
> 
> 
> Traceback (most recent call last):
>   File "heatmap_overlay.py", line 73, in <module>
>     config = yaml.safe_load(stream)
>   File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\__init__.py", line 125, in safe_load
>     return load(stream, SafeLoader)
>   File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\__init__.py", line 79, in load
>     loader = Loader(stream)
>   File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\loader.py", line 34, in __init__
>     Reader.__init__(self, stream)
>   File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\reader.py", line 85, in __init__
>     self.determine_encoding()
>   File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
>     self.update_raw()
>   File "C:\Users\PD\miniconda3\envs\gaze\lib\site-packages\yaml\reader.py", line 178, in update_raw
>     data = self.stream.read(size)
>   File "C:\Users\PD\miniconda3\envs\gaze\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 271: character maps to <undefined>
> ```
> 
> Environment:
> 
> Python 3.8.0 Numpy 1.23.2 Pytorch 1.10.1 (py3.8_cuda11.3_cudnn8_0) Torchvision 0.11.2 (py38_cu113) Opencv-python 4.6.0.66

I edited the following part and the error went away:
~~face=str(sys.argv[1])~~
~~front=str(sys.argv[2])~~
~~output_name=str(sys.argv[3])~~
~~config=str(sys.argv[4])~~
```
def parse_args():
    """Parse input arguments."""
    parser = argparse.ArgumentParser(
        description='heatmap')
    parser.add_argument(
        '--face',dest='face', help='Path of face view video file.', type=str)
    parser.add_argument(
        '--front',dest='front', help='path of front', type=str)
    parser.add_argument(
        '--config',dest='config', help='Path of config file.', type=str)
    parser.add_argument(
        '--output',dest='output', help='Path of output folder.', type=str)

    args = parser.parse_args()
    return args

args = parse_args()

face=args.face
front=args.front
output_name=args.output
config=args.config
```
